apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 932431569521.dkr.ecr.us-east-1.amazonaws.com/shopping-site-electronics:0c83a601c22c0d0c761f4e4f1006f41733bf6a2e
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: electronics-service
  labels:
    app: electronics
spec:
  type: ClusterIP
  selector:
    app: electronics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
